version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/ral
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root